source = ~/.config/hypr/colors.conf

$text_color = $primary
$entry_background_color = $surface_alpha
$entry_border_color = $tertiary
$entry_color = $on_surface
$font_color = $surface
$error_color = $error
$font_family = GeistMono Nerd Font
$font_family_clock = IosevkaTerm Nerd Font
$font_symbols = GeistMono Nerd Font Propo


background {
    path = $image
    blur_passes = 3
    blur_size = 6
}

input-field {
    size = 100, 25
    outline_thickness = 0
    dots_size = 0.3
    dots_space = 0.5
    dots_center = true
    inner_color = $entry_color
    font_color = $font_color
    hide_input = false
    rounding = -1
    check_color = $error_color
    fail_color = $error_color
    fail_transition = 300
    position = 0, -20
    halign = center
    valign = center
}

label {
     monitor =
    text = $TIME
    color = $text_color
    font_size = 100
    font_family = $font_family_clock

    position = 0, 150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}
label { # Date
    monitor =
    text = cmd[update:5000] date +"%A, %B %d"
    color = $entry_border_color
    font_size = 17
    font_family = $font_family

    position = 0, 240
    halign = center
    valign = center
}
label { # User
    monitor =
    text =   $USER 
    color = $entry_color 
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 20
    font_family = $font_symbols
    position = 0, 50
    halign = center
    valign = bottom
}
